dist: trusty
sudo: required
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
# Limit git depth and submodules
git:
  depth: 1
  submodules: false
# addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - gcc-6
#      - g++-6
before_install:
  - sudo apt-get update -qq
  # install dependencies
  - sudo apt-get install -qq libibus-1.0-dev libgtk2.0-dev
  - wget -O autopoint.deb http://mirror.math.princeton.edu/pub/ubuntu/pool/main/g/gettext/autopoint_0.19.7-2ubuntu3_all.deb
  - sudo dpkg -i autopoint.deb
  # for running and testing
  #- sudo apt-get install ibus
  # command to run tests
  # FIXME: add tests
install:
before_script:
  - mkdir build && cd build
script:
  # Link gcc-6 and g++-6 to their standard commands
  # FIXME: Is gcc-6 needed?
  # NOTE: see https://github.com/vn-input/ibus-unikey/issues/9
  #- export CC=gcc-6 CXX=g++-6
  - ../autogen.sh --disable-silent-rules --prefix=/usr --libexec=/usr/lib/ibus || exit 1
  - make -j && sudo make install
  - /usr/lib/ibus/ibus-setup-unikey  --version || exit 1
  - /usr/lib/ibus/ibus-engine-unikey --version || exit 1
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script: